"""

Revision ID: 0a7161354dc8
Revises: 88843daa0733
Create Date: 2020-07-01 16:46:20.399307

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0a7161354dc8'
down_revision = '88843daa0733'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
