"""

Revision ID: 0ae47e8cc0e0
Revises: 29c86643dd99
Create Date: 2020-07-13 10:39:43.232108

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '0ae47e8cc0e0'
down_revision = '29c86643dd99'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    #op.drop_index('ix_department_id', table_name='department')
    #op.drop_index('ix_department_parent_id', table_name='department')
    #op.drop_index('ix_department_status', table_name='department')
    #op.drop_table('department')
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('department',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('order', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('parent_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('name', mysql.DATETIME(), nullable=True),
    sa.Column('end_date', sa.DATE(), nullable=True),
    sa.Column('start_date', sa.DATE(), nullable=True),
    sa.Column('status', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['parent_id'], ['department.id'], name='department_ibfk_1'),
    sa.ForeignKeyConstraint(['status'], ['department.id'], name='department_ibfk_2'),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_index('ix_department_status', 'department', ['status'], unique=False)
    op.create_index('ix_department_parent_id', 'department', ['parent_id'], unique=False)
    op.create_index('ix_department_id', 'department', ['id'], unique=False)
    # ### end Alembic commands ###
