"""

Revision ID: 0dac68944a5c
Revises: 3d10da763575
Create Date: 2020-07-11 23:40:32.827875

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '0dac68944a5c'
down_revision = '3d10da763575'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dict_data', sa.Column('order', sa.Integer(), nullable=True))
    op.drop_column('dict_data', 'sort')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dict_data', sa.Column('sort', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.drop_column('dict_data', 'order')
    # ### end Alembic commands ###
