"""first commit

Revision ID: 142f79231dca
Revises: 520bc0b474b2
Create Date: 2020-06-23 16:32:33.773845

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '142f79231dca'
down_revision = '520bc0b474b2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('avatar', sa.String(length=128), nullable=False))
    op.add_column('user', sa.Column('introduction', sa.String(length=256), nullable=False))
    op.add_column('user', sa.Column('roles', sa.String(length=32), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'roles')
    op.drop_column('user', 'introduction')
    op.drop_column('user', 'avatar')
    # ### end Alembic commands ###
