"""

Revision ID: 273784418566
Revises: f15e96e8c228
Create Date: 2020-06-28 11:13:33.710357

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '273784418566'
down_revision = 'f15e96e8c228'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
