"""

Revision ID: 29c86643dd99
Revises: 7d8b02600f1c
Create Date: 2020-07-13 10:36:17.629851

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '29c86643dd99'
down_revision = '7d8b02600f1c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('department', sa.Column('end_date', sa.Date(), nullable=True))
    op.add_column('department', sa.Column('start_date', sa.Date(), nullable=True))
    op.add_column('department', sa.Column('status', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_department_status'), 'department', ['status'], unique=False)
    op.create_foreign_key(None, 'department', 'department', ['status'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'department', type_='foreignkey')
    op.drop_index(op.f('ix_department_status'), table_name='department')
    op.drop_column('department', 'status')
    op.drop_column('department', 'start_date')
    op.drop_column('department', 'end_date')
    # ### end Alembic commands ###
