"""

Revision ID: 2b0a203b1216
Revises: e1c59550dd51
Create Date: 2020-06-29 10:36:58.714041

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '2b0a203b1216'
down_revision = 'e1c59550dd51'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('role_menu', sa.Column('role_id', sa.Integer(), nullable=True))
    op.add_column('role_menu', sa.Column('role_key', sa.String(length=32), nullable=True))
    op.drop_constraint('role_menu_ibfk_1', 'role_menu', type_='foreignkey')
    op.create_foreign_key(None, 'role_menu', 'role', ['role_id'], ['id'])
    op.drop_column('role_menu', 'group_key')
    op.drop_column('role_menu', 'group_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('role_menu', sa.Column('group_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.add_column('role_menu', sa.Column('group_key', mysql.VARCHAR(length=32), nullable=True))
    op.drop_constraint(None, 'role_menu', type_='foreignkey')
    op.create_foreign_key('role_menu_ibfk_1', 'role_menu', 'role', ['group_id'], ['id'])
    op.drop_column('role_menu', 'role_key')
    op.drop_column('role_menu', 'role_id')
    # ### end Alembic commands ###
