"""

Revision ID: 30efe8b986a6
Revises: e6efe4ba4f0d
Create Date: 2020-06-28 10:12:06.826624

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '30efe8b986a6'
down_revision = 'e6efe4ba4f0d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'menu', 'menu', ['parent_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'menu', type_='foreignkey')
    # ### end Alembic commands ###
