"""

Revision ID: 3161ae076013
Revises: bb6f7651ffa8
Create Date: 2020-07-08 19:34:22.355324

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3161ae076013'
down_revision = 'bb6f7651ffa8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
