"""

Revision ID: 316f08c19996
Revises: cd18d2dcd1fd
Create Date: 2020-06-28 10:19:13.251056

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '316f08c19996'
down_revision = 'cd18d2dcd1fd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
