"""

Revision ID: 386e932f9252
Revises: 39e963f2a90c
Create Date: 2020-07-07 15:38:16.109998

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '386e932f9252'
down_revision = '39e963f2a90c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
