"""

Revision ID: 394872808125
Revises: 9f2fd6206a7d
Create Date: 2020-07-17 16:19:19.102508

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '394872808125'
down_revision = '9f2fd6206a7d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('sex', sa.String(length=8), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'sex')
    # ### end Alembic commands ###
