"""

Revision ID: 3d10da763575
Revises: 4ca67a0be2c7
Create Date: 2020-07-10 12:27:01.445675

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3d10da763575'
down_revision = '4ca67a0be2c7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dict_type',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('code', sa.String(length=32), nullable=True),
    sa.Column('name', sa.String(length=32), nullable=True),
    sa.Column('description', sa.String(length=512), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_dict_type_description'), 'dict_type', ['description'], unique=False)
    op.create_index(op.f('ix_dict_type_id'), 'dict_type', ['id'], unique=False)
    op.create_table('dict_data',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('sort', sa.Integer(), nullable=True),
    sa.Column('label', sa.String(length=128), nullable=True),
    sa.Column('type_id', sa.Integer(), nullable=True),
    sa.Column('css_class', sa.String(length=128), nullable=True),
    sa.Column('list_class', sa.String(length=128), nullable=True),
    sa.Column('is_default', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['type_id'], ['dict_type.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_dict_data_id'), 'dict_data', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_dict_data_id'), table_name='dict_data')
    op.drop_table('dict_data')
    op.drop_index(op.f('ix_dict_type_id'), table_name='dict_type')
    op.drop_index(op.f('ix_dict_type_description'), table_name='dict_type')
    op.drop_table('dict_type')
    # ### end Alembic commands ###
