"""

Revision ID: 42987bba616e
Revises: 57e0de6dd2d7
Create Date: 2020-07-03 23:26:44.060581

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '42987bba616e'
down_revision = '57e0de6dd2d7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
