"""

Revision ID: 4ca67a0be2c7
Revises: 8968295b304b
Create Date: 2020-07-10 12:25:13.009564

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4ca67a0be2c7'
down_revision = '8968295b304b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
