"""

Revision ID: 51c875b43e0e
Revises: e2fdd72b1498
Create Date: 2020-07-13 11:30:07.766209

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '51c875b43e0e'
down_revision = 'e2fdd72b1498'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('department', sa.Column('code', sa.String(length=128), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('department', 'code')
    # ### end Alembic commands ###
