"""intial

Revision ID: 520bc0b474b2
Revises: c31538578e5c
Create Date: 2020-06-22 21:19:41.368802

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '520bc0b474b2'
down_revision = 'c31538578e5c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('item', 'description',
               existing_type=mysql.VARCHAR(length=128),
               type_=sa.String(length=512),
               existing_nullable=True)
    op.alter_column('item', 'title',
               existing_type=mysql.VARCHAR(length=128),
               type_=sa.String(length=32),
               existing_nullable=True)
    op.add_column('user', sa.Column('nickname', sa.String(length=32), nullable=True))
    op.add_column('user', sa.Column('username', sa.String(length=32), nullable=False))
    op.alter_column('user', 'hashed_password',
               existing_type=mysql.VARCHAR(length=128),
               nullable=False)
    op.create_index(op.f('ix_user_nickname'), 'user', ['nickname'], unique=False)
    op.create_index(op.f('ix_user_username'), 'user', ['username'], unique=True)
    op.drop_index('ix_user_email', table_name='user')
    op.drop_index('ix_user_full_name', table_name='user')
    op.drop_column('user', 'full_name')
    op.drop_column('user', 'email')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('email', mysql.VARCHAR(length=128), nullable=True))
    op.add_column('user', sa.Column('full_name', mysql.VARCHAR(length=128), nullable=True))
    op.create_index('ix_user_full_name', 'user', ['full_name'], unique=False)
    op.create_index('ix_user_email', 'user', ['email'], unique=True)
    op.drop_index(op.f('ix_user_username'), table_name='user')
    op.drop_index(op.f('ix_user_nickname'), table_name='user')
    op.alter_column('user', 'hashed_password',
               existing_type=mysql.VARCHAR(length=128),
               nullable=True)
    op.drop_column('user', 'username')
    op.drop_column('user', 'nickname')
    op.alter_column('item', 'title',
               existing_type=sa.String(length=32),
               type_=mysql.VARCHAR(length=128),
               existing_nullable=True)
    op.alter_column('item', 'description',
               existing_type=sa.String(length=512),
               type_=mysql.VARCHAR(length=128),
               existing_nullable=True)
    # ### end Alembic commands ###
