"""

Revision ID: 57e0de6dd2d7
Revises: a53d4c2be17f
Create Date: 2020-07-03 23:23:42.432896

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '57e0de6dd2d7'
down_revision = 'a53d4c2be17f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
