"""

Revision ID: 5c7f63f57fc0
Revises: 0dac68944a5c
Create Date: 2020-07-12 01:14:19.207517

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5c7f63f57fc0'
down_revision = '0dac68944a5c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dict_data', sa.Column('remark', sa.String(length=512), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('dict_data', 'remark')
    # ### end Alembic commands ###
