"""

Revision ID: 5f08629e13f1
Revises: 7af5539ce942
Create Date: 2020-07-03 09:44:30.340070

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5f08629e13f1'
down_revision = '7af5539ce942'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
