"""

Revision ID: 6052d96d32f0
Revises: 4162998bb277
Create Date: 2020-06-28 16:47:40.212163

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6052d96d32f0'
down_revision = '4162998bb277'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
