"""

Revision ID: 766f4180ceb7
Revises: a07a3c6117ba
Create Date: 2020-07-17 17:30:50.463858

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '766f4180ceb7'
down_revision = 'a07a3c6117ba'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
