"""

Revision ID: 7d8b02600f1c
Revises: d6aa555a7a21
Create Date: 2020-07-12 01:23:16.167588

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '7d8b02600f1c'
down_revision = 'd6aa555a7a21'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dict_data', sa.Column('label', sa.String(length=128), nullable=True))
    op.drop_column('dict_data', 'data_label')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dict_data', sa.Column('data_label', mysql.VARCHAR(length=128), nullable=True))
    op.drop_column('dict_data', 'label')
    # ### end Alembic commands ###
