"""

Revision ID: 88843daa0733
Revises: b173755cc795
Create Date: 2020-07-01 16:44:53.740787

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '88843daa0733'
down_revision = 'b173755cc795'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
