"""

Revision ID: 8968295b304b
Revises: 13d7922ac871
Create Date: 2020-07-10 11:05:45.791777

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '8968295b304b'
down_revision = '13d7922ac871'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('menu', 'remark')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('menu', sa.Column('remark', mysql.VARCHAR(length=256), nullable=True))
    # ### end Alembic commands ###
