"""

Revision ID: a53d4c2be17f
Revises: 0df662cd69b7
Create Date: 2020-07-03 22:55:47.165625

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a53d4c2be17f'
down_revision = '0df662cd69b7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('menu', sa.Column('remark', sa.String(length=256), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('menu', 'remark')
    # ### end Alembic commands ###
