"""

Revision ID: a7e509738a06
Revises: 51c875b43e0e
Create Date: 2020-07-14 11:24:56.709736

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a7e509738a06'
down_revision = '51c875b43e0e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_department',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('department_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['department_id'], ['department.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_department_id'), 'user_department', ['id'], unique=False)
    op.create_table('user_dict',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('dict_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['dict_id'], ['dict_data.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_dict_id'), 'user_dict', ['id'], unique=False)
    op.add_column('user', sa.Column('address', sa.String(length=32), nullable=True))
    op.add_column('user', sa.Column('identity_card', sa.String(length=32), nullable=True))
    op.add_column('user', sa.Column('work_start', sa.Date(), nullable=True))
    op.drop_index('ix_user_nickname', table_name='user')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_user_nickname', 'user', ['nickname'], unique=False)
    op.drop_column('user', 'work_start')
    op.drop_column('user', 'identity_card')
    op.drop_column('user', 'address')
    op.drop_index(op.f('ix_user_dict_id'), table_name='user_dict')
    op.drop_table('user_dict')
    op.drop_index(op.f('ix_user_department_id'), table_name='user_department')
    op.drop_table('user_department')
    # ### end Alembic commands ###
