"""

Revision ID: ac7a2a4c8703
Revises: 7936332cb619
Create Date: 2020-06-28 10:51:10.775983

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ac7a2a4c8703'
down_revision = '7936332cb619'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
