"""

Revision ID: b74fe6065021
Revises: ac7a2a4c8703
Create Date: 2020-06-28 10:56:18.892064

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'b74fe6065021'
down_revision = 'ac7a2a4c8703'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    #op.drop_index('ix_menu_parent_id', table_name='menu')
    #op.drop_constraint('menu_ibfk_1', 'menu', type_='foreignkey')
    #op.drop_column('menu', 'parent_id')
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    #op.add_column('menu', sa.Column('parent_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    #op.create_foreign_key('menu_ibfk_1', 'menu', 'menu', ['parent_id'], ['id'])
    #op.create_index('ix_menu_parent_id', 'menu', ['parent_id'], unique=False)
    # ### end Alembic commands ###
