"""

Revision ID: bb6f7651ffa8
Revises: 9644782579b5
Create Date: 2020-07-08 19:31:07.139668

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bb6f7651ffa8'
down_revision = '9644782579b5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('menu', sa.Column('is_frame', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('menu', 'is_frame')
    # ### end Alembic commands ###
