"""first commit

Revision ID: bcdec3973818
Revises: 142f79231dca
Create Date: 2020-06-24 22:18:56.319043

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bcdec3973818'
down_revision = '142f79231dca'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('menu',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=32), nullable=True),
    sa.Column('path', sa.String(length=32), nullable=True),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('order', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_menu_id'), 'menu', ['id'], unique=False)
    op.create_index(op.f('ix_menu_order'), 'menu', ['order'], unique=False)
    op.create_index(op.f('ix_menu_path'), 'menu', ['path'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_menu_path'), table_name='menu')
    op.drop_index(op.f('ix_menu_order'), table_name='menu')
    op.drop_index(op.f('ix_menu_id'), table_name='menu')
    op.drop_table('menu')
    # ### end Alembic commands ###
