"""

Revision ID: bf7d0f5be7d2
Revises: 059ad12c7f53
Create Date: 2020-06-28 16:40:44.298479

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'bf7d0f5be7d2'
down_revision = '059ad12c7f53'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'group_menu', type_='foreignkey')
    op.alter_column('group', 'key',
               existing_type=mysql.VARCHAR(length=32),
               nullable=True)
    # ### end Alembic commands ###
