"""

Revision ID: cc4465cc57a3
Revises: accf91e4afc5
Create Date: 2020-06-26 17:42:04.187308

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cc4465cc57a3'
down_revision = 'accf91e4afc5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('menu', sa.Column('name', sa.String(length=32), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('menu', 'name')
    # ### end Alembic commands ###
