"""

Revision ID: cd18d2dcd1fd
Revises: 250e78708916
Create Date: 2020-06-28 10:18:25.456332

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cd18d2dcd1fd'
down_revision = '250e78708916'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
