"""

Revision ID: d6aa555a7a21
Revises: 5c7f63f57fc0
Create Date: 2020-07-12 01:21:02.613701

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'd6aa555a7a21'
down_revision = '5c7f63f57fc0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dict_data', sa.Column('data_label', sa.String(length=128), nullable=True))
    op.drop_column('dict_data', 'label')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dict_data', sa.Column('label', mysql.VARCHAR(length=128), nullable=True))
    op.drop_column('dict_data', 'data_label')
    # ### end Alembic commands ###
