"""

Revision ID: e2c18ef24967
Revises: 0ae47e8cc0e0
Create Date: 2020-07-13 10:58:04.983167

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e2c18ef24967'
down_revision = '0ae47e8cc0e0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
