"""

Revision ID: e2fdd72b1498
Revises: 0997c9d69092
Create Date: 2020-07-13 11:28:51.357469

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e2fdd72b1498'
down_revision = '0997c9d69092'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
