"""

Revision ID: e6efe4ba4f0d
Revises: cc4465cc57a3
Create Date: 2020-06-26 17:45:46.229878

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e6efe4ba4f0d'
down_revision = 'cc4465cc57a3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('menu', sa.Column('alwaysShow', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('menu', 'alwaysShow')
    # ### end Alembic commands ###
