"""

Revision ID: e8e65909275e
Revises: f6a6e9f4e618
Create Date: 2020-06-28 16:46:09.005950

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e8e65909275e'
down_revision = 'f6a6e9f4e618'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_group_menu_id'), table_name='group_menu')
    op.drop_table('group_menu')
    # ### end Alembic commands ###
