"""

Revision ID: f15e96e8c228
Revises: b74fe6065021
Create Date: 2020-06-28 11:10:48.528144

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f15e96e8c228'
down_revision = 'b74fe6065021'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('menu',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=32), nullable=True),
    sa.Column('title', sa.String(length=32), nullable=True),
    sa.Column('path', sa.String(length=128), nullable=True),
    sa.Column('component', sa.String(length=32), nullable=True),
    sa.Column('hidden', sa.Boolean(), nullable=True),
    sa.Column('alwaysShow', sa.Boolean(), nullable=True),
    sa.Column('icon', sa.String(length=32), nullable=True),
    sa.Column('affix', sa.Boolean(), nullable=True),
    sa.Column('noCache', sa.Boolean(), nullable=True),
    sa.Column('redirect', sa.String(length=32), nullable=True),
    sa.Column('order', sa.Integer(), nullable=True),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['parent_id'], ['menu.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_menu_id'), 'menu', ['id'], unique=False)
    op.create_index(op.f('ix_menu_parent_id'), 'menu', ['parent_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_menu_parent_id'), table_name='menu')
    op.drop_index(op.f('ix_menu_id'), table_name='menu')
    op.drop_table('menu')
    # ### end Alembic commands ###
