"""

Revision ID: f6a6e9f4e618
Revises: 2969d7cfddc2
Create Date: 2020-06-28 16:45:12.389715

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f6a6e9f4e618'
down_revision = '2969d7cfddc2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
