"""

Revision ID: fb7b15f0d050
Revises: 0a7161354dc8
Create Date: 2020-07-01 16:48:11.010138

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fb7b15f0d050'
down_revision = '0a7161354dc8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
